development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: barbera.claudio@gmail.com
  :password:  san.francisco
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: barbera.claudio@gmail.com
  :password:  san.francisco
  :enable_starttls_auto: true